micronaut:
  application:
    name: micronautlin
r2dbc:
  datasources:
    default:
      url: r2dbc:h2:mem:///testdb;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
      schema-generate: CREATE_DROP
      dialect: H2
vertx:
  pg:
    client:
      port: 5432
      host: the-host
      database: the-db
      user: user
      password: password
      maxSize: 5
