micronaut:
  application:
    name: micronautlin
r2dbc:
  datasources:
    default:
      url: r2dbc:postgres://localhost:5432/micronaut
      username: micronaut
      password: micronaut
      schema-generate: CREATE_DROP
      dialect: postgres
